trigger:
- main  # Replace with your branch name

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Debug'
  applicationPackagePath: '$(Build.ArtifactStagingDirectory)\ApplicationPackage'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Match your .NET SDK version

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    clean: true
    restoreNugetPackages: true

# - task: CopyFiles@2
#   inputs:
#     sourceFolder: '$(System.DefaultWorkingDirectory)'
#     contents: '**\ApplicationPackageRoot\**'
#     targetFolder: '$(applicationPackagePath)'

- task: MSBuild@1
  inputs:
    solution: '**/*.sfproj'
    msbuildArguments: '/t:Package /p:Configuration=$(BuildConfiguration) /p:OutDir=$(Build.BinariesDirectory)\'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.BinariesDirectory)\MyApp\pkg\$(BuildConfiguration)'
    artifactName: 'ServiceFabricAppPackage'
    
